#!/bin/bash

rm -f CMakeCache.txt
rm -rf CMakeFiles

SPACK=/noback/nqx/spack/var/spack/environments/dice/.spack-env/view
cmake \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D DICE_TRILINOS_DIR:FILEPATH=$SPACK \
    -D CMAKE_CXX_FLAGS:STRING="-Wno-deprecated-declarations -Wno-format-security" \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="-ljbig -llzma -lz" \
    -D DICE_LIB_DIR:FILEPATH=$DICE/lib \
    -D DICE_HEADER_DIR:FILEPATH=$DICE/include \
    -D DICE_ENABLE_GLOBAL:BOOL=ON \
    -D OpenCV_DIR:PATH=$SPACK \
    ../
    #-D NetCDF_DIR:PATH=<path>/netcdf-4.3.0/install/lib \
    #-D HDF5_DIR:PATH=<path>/hdf5-1.10.1/install/lib \
    #-D OpenCV_DIR:PATH=<path>/opencv-3.2.0/build/install \
