#!/bin/bash

rm -f CMakeCache.txt
rm -rf CMakeFiles
EXTRA_ARGS=$@

SPACK=/noback/nqx/spack/var/spack/environments/dice/.spack-env/view
cmake \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D DICE_TRILINOS_DIR=$SPACK \
    -D CMAKE_INSTALL_PREFIX:FILEPATH=$PWD/../install_ubuntu \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D CMAKE_CXX_FLAGS:STRING="-Wno-deprecated-declarations -Wno-format-security" \
    -D DICE_DEBUG_MSG:BOOL=ON \
    -D DICE_USE_DOUBLE:BOOL=ON \
    -D DICE_USE_TPETRA:BOOL=OFF \
    -D DICE_ENABLE_MANYCORE:BOOL=OFF \
    -D DICE_ENABLE_GLOBAL:BOOL=ON \
    -D OpenCV_DIR:PATH=$SPACK \
    -DBUILD_SHARED_LIBS=ON \
    $EXTRA_ARGS ../
